# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 249af02909eee9b7a16b9904a390df0bca76398ca0d9954eae7250cda9ea8167300d9ac403991691f4e4a7df73efbd3c3faf4e76051b7e315d6ec2381a79010c

test:
  secret_key_base: 3832596789f17a3a1ed9ece0f7beb3628848f01bc1fd888970859f564ff613058e15ae70c32dbff7fe5daf2244b3e60f943d1b25725a93cfbc8481676bd7cffa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
